.class public Lcom/xiaomi/ai/api/Application;
.super Ljava/lang/Object;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/xiaomi/ai/api/Application$WholeHousePlay;,
        Lcom/xiaomi/ai/api/Application$WeixinContactSlot;,
        Lcom/xiaomi/ai/api/Application$WeChatStateInDriveMode;,
        Lcom/xiaomi/ai/api/Application$WakeupSetting;,
        Lcom/xiaomi/ai/api/Application$VoiceWakeupState;,
        Lcom/xiaomi/ai/api/Application$Vibrate;,
        Lcom/xiaomi/ai/api/Application$UserVipState;,
        Lcom/xiaomi/ai/api/Application$UserState;,
        Lcom/xiaomi/ai/api/Application$Translation;,
        Lcom/xiaomi/ai/api/Application$ToneInfo;,
        Lcom/xiaomi/ai/api/Application$TaskState;,
        Lcom/xiaomi/ai/api/Application$SwitchTimeFormat;,
        Lcom/xiaomi/ai/api/Application$SwitchStatus;,
        Lcom/xiaomi/ai/api/Application$StopRelayContent;,
        Lcom/xiaomi/ai/api/Application$State;,
        Lcom/xiaomi/ai/api/Application$SimulateClickV0;,
        Lcom/xiaomi/ai/api/Application$SimulateClickState;,
        Lcom/xiaomi/ai/api/Application$ShowBottomCapture;,
        Lcom/xiaomi/ai/api/Application$ShareWXMiniProgramParam;,
        Lcom/xiaomi/ai/api/Application$ShareStyle;,
        Lcom/xiaomi/ai/api/Application$SharePicParam;,
        Lcom/xiaomi/ai/api/Application$ShareLinkParam;,
        Lcom/xiaomi/ai/api/Application$ShareAnimationParam;,
        Lcom/xiaomi/ai/api/Application$Share;,
        Lcom/xiaomi/ai/api/Application$SetSwitchStatus;,
        Lcom/xiaomi/ai/api/Application$SetBonusAssistantProperty;,
        Lcom/xiaomi/ai/api/Application$ScheduleDuration;,
        Lcom/xiaomi/ai/api/Application$Schedule;,
        Lcom/xiaomi/ai/api/Application$ResourceInfo;,
        Lcom/xiaomi/ai/api/Application$ReportRelayDevices;,
        Lcom/xiaomi/ai/api/Application$RelayContent;,
        Lcom/xiaomi/ai/api/Application$QuickAppState;,
        Lcom/xiaomi/ai/api/Application$QueryBonusAssistant;,
        Lcom/xiaomi/ai/api/Application$PrivacySetting;,
        Lcom/xiaomi/ai/api/Application$PersonalState;,
        Lcom/xiaomi/ai/api/Application$PersonEvent;,
        Lcom/xiaomi/ai/api/Application$OperateWXInDriveMode;,
        Lcom/xiaomi/ai/api/Application$OperateTvApp;,
        Lcom/xiaomi/ai/api/Application$Operate;,
        Lcom/xiaomi/ai/api/Application$MiPlayAudioRelayParam;,
        Lcom/xiaomi/ai/api/Application$MiPlayAudioRelayDevice;,
        Lcom/xiaomi/ai/api/Application$MenstrualData;,
        Lcom/xiaomi/ai/api/Application$MIOTState;,
        Lcom/xiaomi/ai/api/Application$LockScreenFunctionSwitch;,
        Lcom/xiaomi/ai/api/Application$Hint;,
        Lcom/xiaomi/ai/api/Application$GenerateSpeak;,
        Lcom/xiaomi/ai/api/Application$ExpectPush;,
        Lcom/xiaomi/ai/api/Application$ExamInfo;,
        Lcom/xiaomi/ai/api/Application$EnableDriveMode;,
        Lcom/xiaomi/ai/api/Application$DriveModeState;,
        Lcom/xiaomi/ai/api/Application$DisplayAvatarV3;,
        Lcom/xiaomi/ai/api/Application$DisplayAvatarV2;,
        Lcom/xiaomi/ai/api/Application$DisplayAvatar;,
        Lcom/xiaomi/ai/api/Application$DisableDriveMode;,
        Lcom/xiaomi/ai/api/Application$CpState;,
        Lcom/xiaomi/ai/api/Application$CheckAuths;,
        Lcom/xiaomi/ai/api/Application$CheckAppsFailed;,
        Lcom/xiaomi/ai/api/Application$CheckApps;,
        Lcom/xiaomi/ai/api/Application$CheckAppItem;,
        Lcom/xiaomi/ai/api/Application$CheckAppFailedItem;,
        Lcom/xiaomi/ai/api/Application$CancelUserDeviceExecution;,
        Lcom/xiaomi/ai/api/Application$CameraState;,
        Lcom/xiaomi/ai/api/Application$BaikeEvent;,
        Lcom/xiaomi/ai/api/Application$AvatarRequest;,
        Lcom/xiaomi/ai/api/Application$AvatarActionInfo;,
        Lcom/xiaomi/ai/api/Application$AvatarAction;,
        Lcom/xiaomi/ai/api/Application$ApplicationSupport;,
        Lcom/xiaomi/ai/api/Application$ApplicationStatePayload;,
        Lcom/xiaomi/ai/api/Application$ApplicationPhoneCallState;,
        Lcom/xiaomi/ai/api/Application$ApplicationContactListState;,
        Lcom/xiaomi/ai/api/Application$AppState;,
        Lcom/xiaomi/ai/api/Application$AppItem;,
        Lcom/xiaomi/ai/api/Application$AppExtra;,
        Lcom/xiaomi/ai/api/Application$AppDetailV1;,
        Lcom/xiaomi/ai/api/Application$AppDetail;,
        Lcom/xiaomi/ai/api/Application$AdsTrackInfo;,
        Lcom/xiaomi/ai/api/Application$AdsInfo;,
        Lcom/xiaomi/ai/api/Application$WeiXinDriveModeOp;,
        Lcom/xiaomi/ai/api/Application$WXMiniProgramType;,
        Lcom/xiaomi/ai/api/Application$VoiceWakeupType;,
        Lcom/xiaomi/ai/api/Application$UserVipType;,
        Lcom/xiaomi/ai/api/Application$TranslationType;,
        Lcom/xiaomi/ai/api/Application$ToneType;,
        Lcom/xiaomi/ai/api/Application$ToneName;,
        Lcom/xiaomi/ai/api/Application$TTSActionSourceType;,
        Lcom/xiaomi/ai/api/Application$SwitchFeature;,
        Lcom/xiaomi/ai/api/Application$SimulateClickType;,
        Lcom/xiaomi/ai/api/Application$ShareType;,
        Lcom/xiaomi/ai/api/Application$ShareStyleType;,
        Lcom/xiaomi/ai/api/Application$ScheduleTimeType;,
        Lcom/xiaomi/ai/api/Application$ScheduleCircleType;,
        Lcom/xiaomi/ai/api/Application$RelayContentType;,
        Lcom/xiaomi/ai/api/Application$PhoneCallCardMode;,
        Lcom/xiaomi/ai/api/Application$MiPlayAudioRelayDeviceStatus;,
        Lcom/xiaomi/ai/api/Application$MIOTExecuteMode;,
        Lcom/xiaomi/ai/api/Application$HintTag;,
        Lcom/xiaomi/ai/api/Application$ExamName;,
        Lcom/xiaomi/ai/api/Application$ExamEventType;,
        Lcom/xiaomi/ai/api/Application$CpLevel;,
        Lcom/xiaomi/ai/api/Application$CameraModuleType;,
        Lcom/xiaomi/ai/api/Application$CameraLensType;,
        Lcom/xiaomi/ai/api/Application$ApplicationOp;,
        Lcom/xiaomi/ai/api/Application$ApplicationHFPConnectType;,
        Lcom/xiaomi/ai/api/Application$AdsTrackType;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
