.class public Lcom/xiaomi/ai/api/FullScreenTemplate;
.super Ljava/lang/Object;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/xiaomi/ai/api/FullScreenTemplate$WordsDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WordDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WordDeformation;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WeatherIndex;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WeatherFragmentData;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WeatherDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WeatherAlert;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$TranslationDialog;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$TTS;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$SynonymDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$SynonymCard;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Synonym;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Suite;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationRadioInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationCardHead;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationAlbumChapter;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$SimilarMovie;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$RecipeSuggest;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$RecipeListItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$RecipeList;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$RecipeDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$RadioProgram;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$QabotData;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$QabotCpSearchResult;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PrivacyAuthGuide;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PrivacyAuthCardItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemWord;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemVideo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemTailInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemTag;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemSentence;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemParagraph;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemMeaning;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemLocationInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemData;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemAppreciation;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemAnnotates;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemAnnotate;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PhoneticSymbol;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PartSimple;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PartMeaning;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MovieSource;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MovieInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MovieComments;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MovieCommentItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MovieBaseInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Movie;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Message;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MemoInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$JokeData;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Image;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5WordItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Video;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5TranslationV3;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5TranslationV2;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Translation;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Station;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Qabot;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Feihualing;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5DictionaryTarget;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Dictionary;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Dictionaries;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5CourseSchedule;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5ConversationFlow;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Compositions;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Composition;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5AssistMemo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$H5Anniversary;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$FeihualingVerse;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$FeihualingMsg;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$FeihualingLevel;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ExampleSentence;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$EpisodeInfoItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$EpisodeInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$EpisodeDetail;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Emoji;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryWord;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionarySimpleProperty;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryPropertyEvent;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryProperty;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryItem;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryAudioInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Dictionaries;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Dialogue;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Dialog;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CpLauncher;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ConversationFlowTitle;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ConversationFlowText;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ConversationFlowMsg;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ConversationFlowIcon;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CinemaInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CardGuideInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CPInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ArtistInfo;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$AnniversaryReminder;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$Animation;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$WeatherFragmentDataType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$VideoPageType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$SuiteType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationResourceType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationResourceOrderType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationPageType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$StationLiveStatus;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$QabotDataSource;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PrivacyAuthCardType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemTextStyle;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PoemLocationType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$PhoneticType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MessageType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MemoType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$MemoCardType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$FeihualingMsgAlignType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryWordSourceType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryWordCardType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryTargetType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryPropertyType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryItemType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$DictionaryCardType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$ConversationFlowAlignType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CompositionContentType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$CardTextType;,
        Lcom/xiaomi/ai/api/FullScreenTemplate$AnniversaryType;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
