.class public Lcom/xiaomi/ai/api/Nlp;
.super Ljava/lang/Object;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/xiaomi/ai/api/Nlp$WeatherIntention;,
        Lcom/xiaomi/ai/api/Nlp$VoiceIntention;,
        Lcom/xiaomi/ai/api/Nlp$ViolationIntention;,
        Lcom/xiaomi/ai/api/Nlp$VideoIntention;,
        Lcom/xiaomi/ai/api/Nlp$UnexpectedTimes;,
        Lcom/xiaomi/ai/api/Nlp$TransportTicketIntention;,
        Lcom/xiaomi/ai/api/Nlp$TranslationIntention;,
        Lcom/xiaomi/ai/api/Nlp$ToDoListIntention;,
        Lcom/xiaomi/ai/api/Nlp$TimeIntention;,
        Lcom/xiaomi/ai/api/Nlp$SystemAction;,
        Lcom/xiaomi/ai/api/Nlp$StationIntention;,
        Lcom/xiaomi/ai/api/Nlp$StartAnswer;,
        Lcom/xiaomi/ai/api/Nlp$SportsIntention;,
        Lcom/xiaomi/ai/api/Nlp$SoundboxControlIntention;,
        Lcom/xiaomi/ai/api/Nlp$SonglistIntention;,
        Lcom/xiaomi/ai/api/Nlp$SmartAppIntention;,
        Lcom/xiaomi/ai/api/Nlp$SlotValue;,
        Lcom/xiaomi/ai/api/Nlp$SlotState;,
        Lcom/xiaomi/ai/api/Nlp$SecurityIntention;,
        Lcom/xiaomi/ai/api/Nlp$RestrictDrivingIntention;,
        Lcom/xiaomi/ai/api/Nlp$Request;,
        Lcom/xiaomi/ai/api/Nlp$RecipeIntention;,
        Lcom/xiaomi/ai/api/Nlp$RadioIntention;,
        Lcom/xiaomi/ai/api/Nlp$QAIntention;,
        Lcom/xiaomi/ai/api/Nlp$PostBackRequest;,
        Lcom/xiaomi/ai/api/Nlp$PoemIntention;,
        Lcom/xiaomi/ai/api/Nlp$Period;,
        Lcom/xiaomi/ai/api/Nlp$OfflineSkillAction;,
        Lcom/xiaomi/ai/api/Nlp$OfflineSessionItemInfo;,
        Lcom/xiaomi/ai/api/Nlp$OfflineSession;,
        Lcom/xiaomi/ai/api/Nlp$OfflineQueryIntention;,
        Lcom/xiaomi/ai/api/Nlp$OfflineDialogSystemResult;,
        Lcom/xiaomi/ai/api/Nlp$OfflineDialogState;,
        Lcom/xiaomi/ai/api/Nlp$NlpSimpleDevice;,
        Lcom/xiaomi/ai/api/Nlp$NewsIntention;,
        Lcom/xiaomi/ai/api/Nlp$MusicIntention;,
        Lcom/xiaomi/ai/api/Nlp$MapAppIntention;,
        Lcom/xiaomi/ai/api/Nlp$LotteryIntention;,
        Lcom/xiaomi/ai/api/Nlp$LocalStrategy;,
        Lcom/xiaomi/ai/api/Nlp$LoadMore;,
        Lcom/xiaomi/ai/api/Nlp$JokeIntention;,
        Lcom/xiaomi/ai/api/Nlp$InvokeNlpRequest;,
        Lcom/xiaomi/ai/api/Nlp$IntentsWithRelation;,
        Lcom/xiaomi/ai/api/Nlp$IntentionNameItem;,
        Lcom/xiaomi/ai/api/Nlp$HotelIntention;,
        Lcom/xiaomi/ai/api/Nlp$FinishAnswer;,
        Lcom/xiaomi/ai/api/Nlp$FavListIntention;,
        Lcom/xiaomi/ai/api/Nlp$EventACK;,
        Lcom/xiaomi/ai/api/Nlp$EducationIntention;,
        Lcom/xiaomi/ai/api/Nlp$ConstructRequest;,
        Lcom/xiaomi/ai/api/Nlp$ConstellationIntention;,
        Lcom/xiaomi/ai/api/Nlp$BeliefStateV2;,
        Lcom/xiaomi/ai/api/Nlp$BaikeIntention;,
        Lcom/xiaomi/ai/api/Nlp$AuxiliaryIntention;,
        Lcom/xiaomi/ai/api/Nlp$ArithIntention;,
        Lcom/xiaomi/ai/api/Nlp$AgeRange;,
        Lcom/xiaomi/ai/api/Nlp$WeatherSportType;,
        Lcom/xiaomi/ai/api/Nlp$WeatherIntentType;,
        Lcom/xiaomi/ai/api/Nlp$WeatherBroadcastType;,
        Lcom/xiaomi/ai/api/Nlp$VoiceSlotType;,
        Lcom/xiaomi/ai/api/Nlp$ViolationAction;,
        Lcom/xiaomi/ai/api/Nlp$VideoOrder;,
        Lcom/xiaomi/ai/api/Nlp$TravelPreference;,
        Lcom/xiaomi/ai/api/Nlp$TransportType;,
        Lcom/xiaomi/ai/api/Nlp$TransportTicketType;,
        Lcom/xiaomi/ai/api/Nlp$TransportTicketAction;,
        Lcom/xiaomi/ai/api/Nlp$TranslationFuncType;,
        Lcom/xiaomi/ai/api/Nlp$ToDoListAction;,
        Lcom/xiaomi/ai/api/Nlp$TimeUnitType;,
        Lcom/xiaomi/ai/api/Nlp$TimeAction;,
        Lcom/xiaomi/ai/api/Nlp$StockPriceType;,
        Lcom/xiaomi/ai/api/Nlp$StationFilterType;,
        Lcom/xiaomi/ai/api/Nlp$SportsType;,
        Lcom/xiaomi/ai/api/Nlp$SportTargetType;,
        Lcom/xiaomi/ai/api/Nlp$SportSubject;,
        Lcom/xiaomi/ai/api/Nlp$SportStateItem;,
        Lcom/xiaomi/ai/api/Nlp$SportStageType;,
        Lcom/xiaomi/ai/api/Nlp$SportRoleType;,
        Lcom/xiaomi/ai/api/Nlp$SportHomeAway;,
        Lcom/xiaomi/ai/api/Nlp$SportGrainType;,
        Lcom/xiaomi/ai/api/Nlp$SportCompetitionType;,
        Lcom/xiaomi/ai/api/Nlp$SoundboxLoopMode;,
        Lcom/xiaomi/ai/api/Nlp$SongListResourceType;,
        Lcom/xiaomi/ai/api/Nlp$SmartAppHitType;,
        Lcom/xiaomi/ai/api/Nlp$SmartAppActionType;,
        Lcom/xiaomi/ai/api/Nlp$SlotType;,
        Lcom/xiaomi/ai/api/Nlp$SecurityType;,
        Lcom/xiaomi/ai/api/Nlp$SecurityMarketType;,
        Lcom/xiaomi/ai/api/Nlp$SecurityAction;,
        Lcom/xiaomi/ai/api/Nlp$ScreenResolution;,
        Lcom/xiaomi/ai/api/Nlp$RestrictDrivingAction;,
        Lcom/xiaomi/ai/api/Nlp$RecipeAction;,
        Lcom/xiaomi/ai/api/Nlp$PoemType;,
        Lcom/xiaomi/ai/api/Nlp$PoemAction;,
        Lcom/xiaomi/ai/api/Nlp$Payment;,
        Lcom/xiaomi/ai/api/Nlp$OfflineDialogStatus;,
        Lcom/xiaomi/ai/api/Nlp$MapModes;,
        Lcom/xiaomi/ai/api/Nlp$MapAppAction;,
        Lcom/xiaomi/ai/api/Nlp$LotteryType;,
        Lcom/xiaomi/ai/api/Nlp$LotteryCategory;,
        Lcom/xiaomi/ai/api/Nlp$LotteryAction;,
        Lcom/xiaomi/ai/api/Nlp$LocalStrategyType;,
        Lcom/xiaomi/ai/api/Nlp$JokeType;,
        Lcom/xiaomi/ai/api/Nlp$JokeAction;,
        Lcom/xiaomi/ai/api/Nlp$IntentionType;,
        Lcom/xiaomi/ai/api/Nlp$IntentionActionType;,
        Lcom/xiaomi/ai/api/Nlp$HotelType;,
        Lcom/xiaomi/ai/api/Nlp$HotelStarLevel;,
        Lcom/xiaomi/ai/api/Nlp$HotelRoomType;,
        Lcom/xiaomi/ai/api/Nlp$HotelAction;,
        Lcom/xiaomi/ai/api/Nlp$GenderDef;,
        Lcom/xiaomi/ai/api/Nlp$FavListTargetType;,
        Lcom/xiaomi/ai/api/Nlp$FavListActionType;,
        Lcom/xiaomi/ai/api/Nlp$DialogAct;,
        Lcom/xiaomi/ai/api/Nlp$CalendarType;,
        Lcom/xiaomi/ai/api/Nlp$AppName;,
        Lcom/xiaomi/ai/api/Nlp$AddressToModify;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
